/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;

import javax.swing.JOptionPane;
import javax.swing.border.Border;
import koneksi.Koneksi;



/**
 *
 * @author Khoirunnisa
 */
public class Daftar extends javax.swing.JFrame {
    
    private final Connection conn;
    
    /**
     * Creates new form Daftar
     */
    public Daftar() {
        initComponents();
        
        // cek koneksi
        conn = koneksi.Koneksi.cekKoneksi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btn_daftar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_masuk = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        txt_namaLengkap = new javax.swing.JTextField();
        txt_konfPassword = new javax.swing.JPasswordField();
        txt_password = new javax.swing.JPasswordField();
        txt_disini = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        perempuan = new javax.swing.JRadioButton();
        lakiLaki = new javax.swing.JRadioButton();
        bg_daftar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_daftar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_daftar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_daftar_big.png"))); // NOI18N
        btn_daftar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_daftarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_daftarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_daftarMouseExited(evt);
            }
        });
        jPanel1.add(btn_daftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 620, 480, 70));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_daftar.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 40, 120, 50));

        btn_masuk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_masuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_masuk.png"))); // NOI18N
        btn_masuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_masukMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_masukMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_masukMouseExited(evt);
            }
        });
        jPanel1.add(btn_masuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 40, 130, 50));

        txt_username.setBackground(new java.awt.Color(255, 255, 255));
        txt_username.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txt_username.setBorder(null);
        txt_username.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 320, 480, 40));

        txt_namaLengkap.setBackground(new java.awt.Color(255, 255, 255));
        txt_namaLengkap.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txt_namaLengkap.setBorder(null);
        txt_namaLengkap.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_namaLengkap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaLengkapActionPerformed(evt);
            }
        });
        jPanel1.add(txt_namaLengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 230, 480, 40));

        txt_konfPassword.setBackground(new java.awt.Color(255, 255, 255));
        txt_konfPassword.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_konfPassword.setBorder(null);
        jPanel1.add(txt_konfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 500, 480, 40));

        txt_password.setBackground(new java.awt.Color(255, 255, 255));
        txt_password.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_password.setBorder(null);
        jPanel1.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 410, 480, 40));

        txt_disini.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_disini.setForeground(new java.awt.Color(255, 153, 0));
        txt_disini.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_disini.setText("di sini");
        txt_disini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_disiniMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_disiniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_disiniMouseExited(evt);
            }
        });
        jPanel1.add(txt_disini, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 720, 50, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(215, 233, 255));
        jLabel4.setText("Ingin pesan makanan atau minuman? Klik");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 720, -1, -1));

        buttonGroup1.add(perempuan);
        perempuan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        perempuan.setForeground(new java.awt.Color(215, 233, 255));
        perempuan.setText("Perempuan");
        perempuan.setOpaque(false);
        jPanel1.add(perempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 560, -1, -1));

        buttonGroup1.add(lakiLaki);
        lakiLaki.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lakiLaki.setForeground(new java.awt.Color(215, 233, 255));
        lakiLaki.setSelected(true);
        lakiLaki.setText("Laki - Laki");
        lakiLaki.setOpaque(false);
        jPanel1.add(lakiLaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 560, -1, -1));

        bg_daftar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bg_daftar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Daftar.png"))); // NOI18N
        jPanel1.add(bg_daftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_namaLengkapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaLengkapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaLengkapActionPerformed

    private void btn_daftarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_daftarMouseClicked
        // TODO add your handling code here:
        String fname = txt_namaLengkap.getText();
        String username = txt_username.getText();
        String pass1 = String.valueOf(txt_password.getPassword());
        String pass2 = String.valueOf(txt_konfPassword.getPassword());
        String gender = "Laki - Laki";
        
        if(perempuan.isSelected()){
            gender = "Perempuan";
        }
        
        if(verifyFields()){
            if(!checkUsername(username)){
                PreparedStatement ps;
                ResultSet rs;
                String registerUserQuery = "INSERT INTO `admin`(`full_name`, `username`, `password`, `gender`) VALUES (?,?,?,?)";
                
                try {
                    ps = Koneksi.cekKoneksi().prepareStatement(registerUserQuery);
                    ps.setString(1, fname);
                    ps.setString(2, username);
                    ps.setString(3, pass1);
                    ps.setString(4, gender);
                    
                    if(ps.executeUpdate() != 0){
                        JOptionPane.showMessageDialog(null, "Akun Anda Telah Berhasil Dibuat");
                        Login login = new Login();
                        login.setVisible(true);
                        login.pack();
                        login.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Error: Cek Kembali Data Informasi Anda");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Daftar.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btn_daftarMouseClicked

    private void txt_disiniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_disiniMouseEntered
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(255,153,0));
        txt_disini.setBorder(label_border);
    }//GEN-LAST:event_txt_disiniMouseEntered

    private void txt_disiniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_disiniMouseExited
        // TODO add your handling code here:
        txt_disini.setBorder(null);
    }//GEN-LAST:event_txt_disiniMouseExited

    private void btn_masukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_masukMouseClicked
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        login.pack();
        login.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btn_masukMouseClicked

    private void txt_disiniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_disiniMouseClicked
        // TODO add your handling code here:
        User user = new User();
        user.setVisible(true);
        user.pack();
        user.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_txt_disiniMouseClicked

    private void btn_daftarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_daftarMouseEntered
        // TODO add your handling code here:
        btn_daftar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_daftar_big_hover.png"))); // NOI18N
    }//GEN-LAST:event_btn_daftarMouseEntered

    private void btn_daftarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_daftarMouseExited
        // TODO add your handling code here:
        btn_daftar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_daftar_big.png"))); // NOI18N
    }//GEN-LAST:event_btn_daftarMouseExited

    private void btn_masukMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_masukMouseEntered
        // TODO add your handling code here:
        btn_masuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_masuk_hover_forDaftar.png"))); // NOI18N
        
    }//GEN-LAST:event_btn_masukMouseEntered

    private void btn_masukMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_masukMouseExited
        // TODO add your handling code here:
        btn_masuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_masuk.png"))); // NOI18N
    }//GEN-LAST:event_btn_masukMouseExited

    
    //create function to verify the empty fields
    public boolean verifyFields(){
        String fname = txt_namaLengkap.getText();
        String uname = txt_username.getText();
        String pass1 = String.valueOf(txt_password.getPassword());
        String pass2 = String.valueOf(txt_konfPassword.getPassword());
        
        if(fname.trim().equals("") || uname.trim().equals("") || pass1.trim().equals("") || pass2.trim().equals("")){
            JOptionPane.showMessageDialog(null, "Terdapat Data yang Belum Diisi","Data kosong",2);
            return false;
        }
        //check if two password are equals
        else if(!pass1.equals(pass2)) {
            JOptionPane.showMessageDialog(null, "Password Tidak Sama","Konfirmasi Password",2);
            return false;
        }
        //if all is well
        else {
            return true;
        }
    }
    
    
    //create function to check if the entered username already exists
    public boolean checkUsername(String username){
        PreparedStatement st;
        ResultSet rs;
        boolean username_exist = false;
            
        String query = "SELECT * FROM `admin` WHERE `username` = ?";
            
        try {
            st = Koneksi.cekKoneksi().prepareStatement(query);
            st.setString(1, username);
            rs = st.executeQuery();
            
            if(rs.next()){
                username_exist = true;
                JOptionPane.showMessageDialog(null, "Username Telah Digunakan", "Username Gagal", 2);
            } 
        } catch (SQLException ex) {
            Logger.getLogger(Daftar.class.getName()).log(Level.SEVERE, null, ex);
        }
        return username_exist;
    }
    
    /**
     * @param args the command line arguments
     */
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Daftar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_daftar;
    private javax.swing.JLabel btn_daftar;
    private javax.swing.JLabel btn_masuk;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton lakiLaki;
    private javax.swing.JRadioButton perempuan;
    private javax.swing.JLabel txt_disini;
    private javax.swing.JPasswordField txt_konfPassword;
    private javax.swing.JTextField txt_namaLengkap;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
