/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.sql.Connection;
import javax.swing.JFrame;

/**
 *
 * @author Khoirunnisa
 */
public class Home extends javax.swing.JFrame {
    private final Connection conn;
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        
        // cek koneksi
        conn = koneksi.Koneksi.cekKoneksi();
    }
    
    
    
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_order = new javax.swing.JLabel();
        bg_home = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/KMP_1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        btn_order.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_order.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_order.png"))); // NOI18N
        btn_order.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_orderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_orderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_orderMouseExited(evt);
            }
        });
        jPanel1.add(btn_order, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, -1, -1));

        bg_home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bg_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SelamatDatang.png"))); // NOI18N
        jPanel1.add(bg_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 790));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1255, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 774, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_orderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_orderMouseClicked
        // TODO add your handling code here:
        User user = new User();
        user.setVisible(true);
        user.pack();
        user.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btn_orderMouseClicked

    private void btn_orderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_orderMouseEntered
        // TODO add your handling code here:
        btn_order.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_order_hover.png"))); // NOI18N
    }//GEN-LAST:event_btn_orderMouseEntered

    private void btn_orderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_orderMouseExited
        // TODO add your handling code here:
        btn_order.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_order.png"))); // NOI18N
    }//GEN-LAST:event_btn_orderMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_home;
    private javax.swing.JLabel btn_order;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
